services:
  code-server:
    image: fabianhk/dystar-with-code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DEFAULT_WORKSPACE=/home/user/workspace
    volumes:
      - $PWD/workspace:/home/user/workspace
    ports:
      - 127.0.0.1:8443:8443
    restart: unless-stopped
